repos:
 - repo: https://github.com/psf/black
   rev: 21.5b1 # Use tags based on https://github.com/psf/black/tags
   hooks:
    - id: black
      language_version: python3
      args: [app.py, dashutils/, api/, config/]
 - repo: https://github.com/PyCQA/flake8.git
   rev: 3.9.2
   hooks:
    - id: flake8
      language_version: python3